name: Python CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: install packages
      uses: make install

    - name: lint
      uses: make lint

    - name: test
      run: make test

    - name: format
      run: make format

    - name: run
      run: make run 

      

